### PR TITLE
Added Hyperlink Support, Corrected Typos, and Introduced New Question

### PR DESCRIPTION
**Pull request by Congiuntivo**
This pull request adds the hyperref package to the LaTeX document, making the Table of Contents (TOC) interactive with clickable links. This enhancement simplifies document navigation without altering the layout or formatting.

### CODE REVIEW

**Comment by Congiuntivo** [comment]
I've gone ahead and fixed a few typos in the document. Additionally, I've included a new question from the January 2023 exam.

**Comment by matteounitn** [comment]
The tex file is supportive of the markdown one. Can you add the changes to the markdown?

**Comment by Congiuntivo** [comment]
Sure

**Comment by Congiuntivo** [comment]
I've just updated the markdown file. I'll leave it to you to generate the HTML, unless you provide me with the Pandoc recipe / CSS.

**Comment by matteounitn** [comment]
By checking, I see that the markdown is different from the TEX update. On the TEX, we have the RSA fix, but not in the MD. Am I right?

**Comment by Congiuntivo** [comment]
After some time, I finally did it.

**Pull request merged**
